# Herbal Retrieval System

## Information Retrieval Project

**Nama:** Adhi Prasetyo

**NIM:** 32602400071

**Mata Kuliah:** Information Retrieval

---

### Tema

Sistem Pencarian Tanaman Obat Indonesia
menggunakan TF-IDF dan Cosine Similarity

## Deskripsi

Project ini merupakan implementasi sederhana sistem Information Retrieval untuk mencari tanaman obat Indonesia berdasarkan khasiat yang dimiliki.

Sistem menggunakan:

- Text Preprocessing
- TF-IDF
- Cosine Similarity
- Vector Space Model

Output berupa rekomendasi tanaman obat yang paling relevan terhadap query pengguna.

# Tahap 1
## Import Library

Library yang digunakan:

- pandas
- re
- nltk (stopword)
- sklearn

Library sklearn digunakan untuk TF-IDF dan Cosine Similarity.

In [73]:
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.metrics.pairwise import cosine_similarity

In [74]:
data = {
    "Tanaman": [
        "Jahe",
        "Kunyit",
        "Temulawak",
        "Daun Sirih",
        "Sambiloto",
        "Lidah Buaya",
        "Kencur",
        "Pegagan",
        "Meniran",
        "Daun Jambu"
    ],

    "Khasiat": [

        "mengatasi masuk angin mual batuk menghangatkan tubuh",

        "antiinflamasi maag nyeri sendi antioksidan",

        "menjaga kesehatan hati meningkatkan nafsu makan",

        "antiseptik sariawan bau mulut luka",

        "menurunkan gula darah meningkatkan daya tahan tubuh",

        "luka bakar kesehatan kulit rambut",

        "batuk masuk angin pegal linu",

        "meningkatkan daya ingat penyembuhan luka",

        "meningkatkan sistem imun infeksi virus",

        "diare sakit perut"
    ]
}

df = pd.DataFrame(data)

# Tahap 2
## Dataset

Dataset berisi informasi beberapa tanaman obat Indonesia beserta khasiatnya.

Kolom:

- Tanaman
- Khasiat

In [75]:
df

       Tanaman                                            Khasiat
0         Jahe  mengatasi masuk angin mual batuk menghangatkan...
1       Kunyit         antiinflamasi maag nyeri sendi antioksidan
2    Temulawak    menjaga kesehatan hati meningkatkan nafsu makan
3   Daun Sirih                 antiseptik sariawan bau mulut luka
4    Sambiloto  menurunkan gula darah meningkatkan daya tahan ...
5  Lidah Buaya                  luka bakar kesehatan kulit rambut
6       Kencur                       batuk masuk angin pegal linu
7      Pegagan           meningkatkan daya ingat penyembuhan luka
8      Meniran             meningkatkan sistem imun infeksi virus
9   Daun Jambu                                  diare sakit perut

# Tahap 3
## Text Preprocessing

Tahapan preprocessing:

1. Case Folding
2. Remove Punctuation
3. Tokenization
4. Stopword Removal

Tujuan preprocessing adalah membersihkan teks agar proses pencarian menjadi lebih akurat.

In [76]:
import re
import nltk

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [77]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [78]:
stop_words = set(stopwords.words('indonesian'))

print(stop_words)

{'memperkirakan', 'bersama', 'siapapun', 'bisa', 'diingat', 'kecil', 'sana', 'menuturkan', 'sebaik', 'berkenaan', 'pernah', 'lainnya', 'sambil', 'wong', 'bukannya', 'masalah', 'mendapat', 'terjadinya', 'jadilah', 'sudahlah', 'selama-lamanya', 'tahun', 'kini', 'selamanya', 'semisalnya', 'enggaknya', 'belakang', 'jangan', 'melainkan', 'memberi', 'umum', 'kalian', 'teringat', 'sangat', 'berakhirlah', 'seingat', 'seseorang', 'percuma', 'melihatnya', 'dibuatnya', 'misalkan', 'sedikit', 'meski', 'terasa', 'keterlaluan', 'tambah', 'tepat', 'sebenarnya', 'per', 'sekalipun', 'mungkinkah', 'mendatangkan', 'dialah', 'dimaksud', 'mengakhiri', 'sampai', 'berjumlah', 'belum', 'menambahkan', 'keadaan', 'katakan', 'inginkan', 'meyakini', 'sedangkan', 'ujar', 'dijelaskannya', 'saatnya', 'enggak', 'bahkan', 'dahulu', 'jumlahnya', 'rupanya', 'sepantasnyalah', 'selama', 'seberapa', 'tidaklah', 'ditunjuknya', 'tersebut', 'sela', 'naik', 'mengetahui', 'keinginan', 'hanya', 'sebelum', 'nanti', 'lalu', 'berbagai', 'banyak', 'berlebihan', 'dapat', 'hal', 'amatlah', 'ibu', 'kamulah', 'malahan', 'semakin', 'berawal', 'lanjut', 'dilakukan', 'bapak', 'boleh', 'bagaimana', 'merupakan', 'tahu', 'tersampaikan', 'menjadi', 'ditujukan', 'mulailah', 'sudahkah', 'oleh', 'buat', 'ditunjukkan', 'ingin', 'tutur', 'sebegitu', 'kelamaan', 'setibanya', 'dipersoalkan', 'sebegini', 'sepihak', 'mulai', 'belakangan', 'pihak', 'ditambahkan', 'meminta', 'beginian', 'tiga', 'lain', 'bulan', 'jangankan', 'sebuah', 'berturut-turut', 'gunakan', 'tadi', 'seluruh', 'agaknya', 'kok', 'dimulainya', 'kebetulan', 'sejauh', 'berikan', 'disinilah', 'walaupun', 'sebisanya', 'manakala', 'apakah', 'beri', 'awalnya', 'kalau', 'sesama', 'tetap', 'diperlukannya', 'hingga', 'dikarenakan', 'memisalkan', 'ternyata', 'segala', 'tampaknya', 'betulkah', 'andalah', 'begitu', 'semacam', 'rata', 'memperlihatkan', 'kepadanya', 'berkata', 'dari', 'hendak', 'tampak', 'mengibaratkannya', 'semua', 'ungkap', 'dipertanyakan', 'kalaulah', 'menyiapkan', 'itu', 'demi', 'merekalah', 'inginkah', 'akhiri', 'mempunyai', 'itukah', 'perlu', 'jelasnya', 'tapi', 'minta', 'semaunya', 'tanpa', 'jadi', 'diucapkan', 'secukupnya', 'besar', 'dilalui', 'mula', 'tengah', 'soal', 'sebagai', 'mempergunakan', 'terkira', 'siapakah', 'mana', 'beginikah', 'artinya', 'dituturkannya', 'ucapnya', 'diketahuinya', 'kapanpun', 'rasa', 'tetapi', 'sampai-sampai', 'penting', 'bakalan', 'bolehkah', 'balik', 'kembali', 'apaan', 'diungkapkan', 'mengapa', 'kepada', 'memulai', 'menantikan', 'dia', 'setiba', 'segera', 'dalam', 'sama', 'asalkan', 'jelaslah', 'mengerjakan', 'dimintai', 'bakal', 'yaitu', 'kira', 'namun', 'kemudian', 'masing-masing', 'perlunya', 'ditunjuk', 'seorang', 'tentunya', 'mengibaratkan', 'diberikan', 'kan', 'bolehlah', 'dimungkinkan', 'sekaligus', 'dimaksudkannya', 'keduanya', 'jikalau', 'terjadi', 'padanya', 'sayalah', 'diperlukan', 'awal', 'maka', 'depan', 'setengah', 'bagaimanapun', 'semula', 'berada', 'mengatakan', 'pasti', 'caranya', 'mulanya', 'wahai', 'sepantasnya', 'sejenak', 'semuanya', 'dini', 'ditanya', 'beberapa', 'siapa', 'dimulailah', 'katanya', 'menunjuk', 'berikutnya', 'memerlukan', 'kami', 'daripada', 'inilah', 'tentu', 'dikerjakan', 'serta', 'berapakah', 'para', 'itulah', 'ditegaskan', 'secara', 'sekiranya', 'harus', 'kata', 'jauh', 'sesuatunya', 'tentulah', 'sekarang', 'kelima', 'akhirnya', 'semata-mata', 'seolah', 'setidak-tidaknya', 'kamu', 'jika', 'tidak', 'sebagaimana', 'dipunyai', 'kamilah', 'pak', 'mirip', 'serupa', 'sebelumnya', 'menghendaki', 'begini', 'diperbuatnya', 'kenapa', 'keseluruhannya', 'mengatakannya', 'menyatakan', 'usai', 'demikianlah', 'biasanya', 'sekurangnya', 'bermacam', 'hampir', 'mengingatkan', 'mengenai', 'cukup', 'disebut', 'kemungkinan', 'toh', 'disebutkannya', 'karenanya', 'teringat-ingat', 'segalanya', 'entah', 'sendirian', 'atas', 'waduh', 'setempat', 'bagaimanakah', 'kelihatan', 'mendatangi', 'berupa', 'manalagi', 'baru', 'kapankah', 'membuat', 'lanjutnya', 'malah', 'disampaikan', 'mengingat', 'bertanya', 'mengucapkannya', 'menyangkut', 'supaya', 'terus', 'tandasnya', 'seterusnya', 'antar', 'waktu', 'menyebutkan', 'bermacam-macam', 'menanya', 'guna', 'terbanyak', 'anda', 'sekali', 'berapapun', 'nah', 'selaku', 'terjadilah', 'atau', 'berujar', 'ditandaskan', 'sekalian', 'melihat', 'apa', 'bahwasanya', 'dan', 'amat', 'dirinya', 'terdahulu', 'diberikannya', 'setidaknya', 'karena', 'tandas', 'menggunakan', 'makin', 'kurang', 'perlukah', 'sehingga', 'berikut', 'melakukan', 'sebesar', 'agak', 'berdatangan', 'dikira', 'kemungkinannya', 'misalnya', 'mengungkapkan', 'sama-sama', 'dong', 'sempat', 'mengucapkan', 'persoalan', 'sedemikian', 'dengan', 'berkali-kali', 'lima', 'diberi', 'sebab', 'berapa', 'diibaratkan', 'menanyakan', 'memang', 'semata', 'wah', 'jawaban', 'saja', 'ikut', 'seusai', 'mereka', 'sesudahnya', 'menanti', 'hari', 'tentang', 'khususnya', 'yakni', 'keseluruhan', 'tunjuk', 'pentingnya', 'sebaik-baiknya', 'ungkapnya', 'biasa', 'datang', 'menuju', 'kapan', 'hendaknya', 'benar', 'meyakinkan', 'sudah', 'sendirinya', 'empat', 'benarlah', 'kinilah', 'betul', 'sedikitnya', 'terlihat', 'cara', 'lagi', 'sesegera', 'adanya', 'misal', 'diantara', 'sesudah', 'memperbuat', 'tertentu', 'menyeluruh', 'bagi', 'dimaksudnya', 'hendaklah', 'ini', 'hanyalah', 'pun', 'begitupun', 'sangatlah', 'pertanyaan', 'sebutnya', 'apabila', 'diketahui', 'dijawab', 'jelaskan', 'seolah-olah', 'dimulai', 'ujarnya', 'dimaksudkan', 'bawah', 'kiranya', 'berapalah', 'suatu', 'didapat', 'sebagainya', 'disebutkan', 'seharusnya', 'akhir', 'bertanya-tanya', 'masa', 'menjelaskan', 'tinggi', 'sekali-kali', 'terlalu', 'sebaliknya', 'rasanya', 'baik', 'diinginkan', 'semasa', 'jelas', 'dipergunakan', 'merasa', 'mendapatkan', 'seperlunya', 'usah', 'bisakah', 'terdapat', 'maupun', 'ibaratnya', 'sebetulnya', 'sebutlah', 'umumnya', 'tertuju', 'sesekali', 'memintakan', 'sajalah', 'untuk', 'sekadarnya', 'terdiri', 'diminta', 'dulu', 'ditunjuki', 'menyampaikan', 'sesaat', 'melalui', 'terhadap', 'diakhirinya', 'pantas', 'setelah', 'semampu', 'yang', 'terhadapnya', 'nyaris', 'berakhir', 'bekerja', 'sepertinya', 'luar', 'paling', 'begitukah', 'kelihatannya', 'sementara', 'diperlihatkan', 'begitulah', 'bagian', 'sesuatu', 'dikatakannya', 'janganlah', 'lagian', 'memungkinkan', 'akulah', 'cukupkah', 'sewaktu', 'ingat-ingat', 'bersama-sama', 'belumlah', 'mau', 'pihaknya', 'tegasnya', 'apatah', 'bersiap', 'masih', 'sekecil', 'sini', 'olehnya', 'pastilah', 'semisal', 'jumlah', 'selanjutnya', 'ialah', 'sinilah', 'dijelaskan', 'termasuk', 'kitalah', 'jawab', 'ibaratkan', 'bilakah', 'saat', 'memastikan', 'selalu', 'kasus', 'sejumlah', 'ia', 'tanyakan', 'soalnya', 'menunjuknya', 'ingat', 'kira-kira', 'pula', 'tiap', 'cuma', 'dekat', 'diingatkan', 'sebanyak', 'diibaratkannya', 'adalah', 'bersiap-siap', 'akan', 'macam', 'sesampai', 'setiap', 'terakhir', 'terutama', 'akankah', 'turut', 'pukul', 'diperkirakan', 'bagaikan', 'dilihat', 'dituturkan', 'tanyanya', 'panjang', 'antaranya', 'selain', 'sendiri', 'setinggi', 'punya', 'tiba', 'bertutur', 'disini', 'pertanyakan', 'sebagian', 'ucap', 'ataupun', 'ataukah', 'sepanjang', 'seperti', 'pertama', 'tidakkah', 'diperbuat', 'menandaskan', 'pertama-tama', 'bukan', 'mampukah', 'beginilah', 'berkeinginan', 'jadinya', 'lamanya', 'menunjukkan', 'dimisalkan', 'digunakan', 'kedua', 'didatangkan', 'ditanyai', 'lebih', 'tempat', 'berarti', 'menanti-nanti', 'semampunya', 'jawabnya', 'sebabnya', 'pada', 'adapun', 'masihkah', 'harusnya', 'ditunjukkannya', 'kala', 'ibarat', 'masing', 'menunjuki', 'diri', 'bermaksud', 'antara', 'inikah', 'ke', 'juga', 'sampaikan', 'kalaupun', 'demikian', 'asal', 'menanyai', 'mempertanyakan', 'satu', 'dipastikan', 'entahlah', 'sekadar', 'berlainan', 'tadinya', 'bukankah', 'justru', 'diucapkannya', 'sebut', 'kita', 'aku', 'berakhirnya', 'mungkin', 'ketika', 'seketika', 'haruslah', 'bila', 'ditanyakan', 'diantaranya', 'tegas', 'berlalu', 'semasih', 'sejak', 'sering', 'seluruhnya', 'berlangsung', 'tak', 'diakhiri', 'sebaiknya', 'telah', 'lewat', 'tiba-tiba', 'mampu', 'lah', 'saya', 'memberikan', 'mempersiapkan', 'dikatakan', 'katakanlah', 'mempersoalkan', 'keluar', 'sekitar', 'menegaskan', 'bagai', 'berturut', 'meskipun', 'siap', 'menjawab', 'mengira', 'ada', 'berkehendak', 'nyatanya', 'bermula', 'dibuat', 'bung', 'masalahnya', 'waktunya', 'nantinya', 'di', 'sekurang-kurangnya', 'dua', 'lama', 'mendatang', 'menurut', 'seringnya', 'seenaknya', 'makanya', 'yakin', 'memihak', 'bahwa', 'menaiki', 'se', 'terlebih', 'cukuplah', 'saling', 'padahal', 'apalagi', 'menginginkan', 'bukanlah', 'tambahnya', 'tanya', 'tersebutlah', 'sedang', 'sekitarnya', 'agar', 'kesampaian', 'walau', 'benarkah', 'tuturnya'}

In [79]:
def preprocessing(text):

    # 1. Case Folding
    text = text.lower()

    # 2. Hapus tanda baca
    text = re.sub(r'[^a-zA-Z\s]', '', text)

    # 3. Tokenisasi sederhana
    tokens = text.split()

    # 4. Stopword Removal
    tokens = [word for word in tokens if word not in stop_words]

    return " ".join(tokens)

In [80]:
df["Clean_Text"] = df["Khasiat"].apply(preprocessing)

df

,Tanaman,Khasiat,Clean_Text
0,Jahe,mengatasi masuk angin mual batuk menghangatkan...,mengatasi masuk angin mual batuk menghangatkan...
1,Kunyit,antiinflamasi maag nyeri sendi antioksidan,antiinflamasi maag nyeri sendi antioksidan
2,Temulawak,menjaga kesehatan hati meningkatkan nafsu makan,menjaga kesehatan hati meningkatkan nafsu makan
3,Daun Sirih,antiseptik sariawan bau mulut luka,antiseptik sariawan bau mulut luka
4,Sambiloto,menurunkan gula darah meningkatkan daya tahan ...,menurunkan gula darah meningkatkan daya tahan ...
5,Lidah Buaya,luka bakar kesehatan kulit rambut,luka bakar kesehatan kulit rambut
6,Kencur,batuk masuk angin pegal linu,batuk masuk angin pegal linu
7,Pegagan,meningkatkan daya ingat penyembuhan luka,meningkatkan daya penyembuhan luka
8,Meniran,meningkatkan sistem imun infeksi virus,meningkatkan sistem imun infeksi virus
9,Daun Jambu,diare sakit perut,diare sakit perut

# Tahap 4
## Representasi Dokumen

Dokumen direpresentasikan menggunakan metode TF-IDF (Term Frequency Inverse Document Frequency).

TF-IDF memberikan bobot yang lebih besar pada kata yang penting dan lebih kecil pada kata yang sering muncul.

In [81]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Membuat objek TF-IDF
vectorizer = TfidfVectorizer()

# Mengubah dokumen menjadi matriks TF-IDF
tfidf_matrix = vectorizer.fit_transform(df["Clean_Text"])

print("TF-IDF berhasil dibuat!")

TF-IDF berhasil dibuat!

In [82]:
feature_names = vectorizer.get_feature_names_out()

print(feature_names)

['angin' 'antiinflamasi' 'antioksidan' 'antiseptik' 'bakar' 'batuk' 'bau'
 'darah' 'daya' 'diare' 'gula' 'hati' 'imun' 'infeksi' 'kesehatan' 'kulit'
 'linu' 'luka' 'maag' 'makan' 'masuk' 'mengatasi' 'menghangatkan'
 'meningkatkan' 'menjaga' 'menurunkan' 'mual' 'mulut' 'nafsu' 'nyeri'
 'pegal' 'penyembuhan' 'perut' 'rambut' 'sakit' 'sariawan' 'sendi'
 'sistem' 'tahan' 'tubuh' 'virus']

In [83]:
tfidf_df = pd.DataFrame(
    tfidf_matrix.toarray(),
    columns=feature_names,
    index=df["Tanaman"]
)

tfidf_df

,angin,antiinflamasi,antioksidan,antiseptik,bakar,batuk,bau,darah,daya,diare,...,penyembuhan,perut,rambut,sakit,sariawan,sendi,sistem,tahan,tubuh,virus
Tanaman,,,,,,,,,,,,,,,,,,,,,
Jahe,0.350256,0.000000,0.000000,0.000000,0.000000,0.350256,0.000000,0.000000,0.000000,0.00000,...,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.350256,0.000000
Kunyit,0.000000,0.447214,0.447214,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,...,0.000000,0.00000,0.000000,0.00000,0.000000,0.447214,0.000000,0.000000,0.000000,0.000000
Temulawak,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,...,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Daun Sirih,0.000000,0.000000,0.000000,0.468646,0.000000,0.000000,0.468646,0.000000,0.000000,0.00000,...,0.000000,0.00000,0.000000,0.00000,0.468646,0.000000,0.000000,0.000000,0.000000,0.000000
Sambiloto,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.412304,0.350496,0.00000,...,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000,0.412304,0.350496,0.000000
Lidah Buaya,0.000000,0.000000,0.000000,0.000000,0.483606,0.000000,0.000000,0.000000,0.000000,0.00000,...,0.000000,0.00000,0.483606,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Kencur,0.416393,0.000000,0.000000,0.000000,0.000000,0.416393,0.000000,0.000000,0.000000,0.00000,...,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Pegagan,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.516107,0.00000,...,0.607119,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Meniran,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,...,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.474727,0.000000,0.000000,0.474727
Daun Jambu,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.57735,...,0.000000,0.57735,0.000000,0.57735,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

# Tahap 5
## Information Retrieval

Model yang digunakan adalah:

Vector Space Model

Kesamaan antara query dan dokumen dihitung menggunakan Cosine Similarity.

In [84]:
print(tfidf_matrix.shape)

(10, 41)

In [85]:
def search(query):

    # Preprocessing query
    query = preprocessing(query)

    # Ubah query menjadi TF-IDF
    query_vector = vectorizer.transform([query])

    # Hitung cosine similarity
    similarity = cosine_similarity(query_vector, tfidf_matrix)

    return similarity

In [86]:
query = "masuk angin"

similarity = search(query)

print(similarity)

[[0.49533618 0.         0.         0.         0.         0.
  0.58886876 0.         0.         0.        ]]

In [87]:
result = pd.DataFrame({
    "Tanaman": df["Tanaman"],
    "Similarity": similarity.flatten()
})

result

       Tanaman  Similarity
0         Jahe    0.495336
1       Kunyit    0.000000
2    Temulawak    0.000000
3   Daun Sirih    0.000000
4    Sambiloto    0.000000
5  Lidah Buaya    0.000000
6       Kencur    0.588869
7      Pegagan    0.000000
8      Meniran    0.000000
9   Daun Jambu    0.000000

In [88]:
result = result.sort_values(
    by="Similarity",
    ascending=False
)

result

       Tanaman  Similarity
6       Kencur    0.588869
0         Jahe    0.495336
1       Kunyit    0.000000
2    Temulawak    0.000000
4    Sambiloto    0.000000
3   Daun Sirih    0.000000
5  Lidah Buaya    0.000000
7      Pegagan    0.000000
8      Meniran    0.000000
9   Daun Jambu    0.000000

In [89]:
result.head(5)

     Tanaman  Similarity
6     Kencur    0.588869
0       Jahe    0.495336
1     Kunyit    0.000000
2  Temulawak    0.000000
4  Sambiloto    0.000000

In [90]:
print("=" * 50)
print("🌿 HERBAL RETRIEVAL SYSTEM")
print("=" * 50)

query = input("Masukkan penyakit atau khasiat yang ingin dicari: ")

==================================================
🌿 HERBAL RETRIEVAL SYSTEM
==================================================
Masukkan penyakit atau khasiat yang ingin dicari: maag

In [91]:
similarity = search(query)

result = pd.DataFrame({
    "Tanaman": df["Tanaman"],
    "Khasiat": df["Khasiat"],
    "Similarity": similarity.flatten()
})

result = result.sort_values(
    by="Similarity",
    ascending=False
)

In [92]:
print("\nTop 5 Tanaman Obat Paling Relevan\n")

display(result.head(5))

Top 5 Tanaman Obat Paling Relevan

      Tanaman                                            Khasiat  Similarity
1      Kunyit         antiinflamasi maag nyeri sendi antioksidan    0.447214
0        Jahe  mengatasi masuk angin mual batuk menghangatkan...    0.000000
2   Temulawak    menjaga kesehatan hati meningkatkan nafsu makan    0.000000
3  Daun Sirih                 antiseptik sariawan bau mulut luka    0.000000
4   Sambiloto  menurunkan gula darah meningkatkan daya tahan ...    0.000000

In [93]:
print("\n==============================")
print("HASIL PENCARIAN")
print("==============================")

top5 = result[result["Similarity"] > 0].head(5)

if top5.empty:
    print("\nTidak ditemukan tanaman yang sesuai.")
else:
    for i, row in enumerate(top5.itertuples(), start=1):
        print(f"\n{i}. {row.Tanaman}")
        print(f"   Similarity : {row.Similarity:.4f}")
        print(f"   Khasiat    : {row.Khasiat}")

==============================
HASIL PENCARIAN
==============================

1. Kunyit
   Similarity : 0.4472
   Khasiat    : antiinflamasi maag nyeri sendi antioksidan

# Kesimpulan

Sistem berhasil melakukan:

- preprocessing
- representasi dokumen menggunakan TF-IDF
- pencarian dokumen
- ranking dokumen menggunakan cosine similarity

Semakin besar nilai similarity maka semakin relevan tanaman obat terhadap query pengguna.